### ISSUE TITLE
Errors in Hugging Face interface

### ISSUE THREAD

**Issue by vivekJax** [gaomingqi/Track-Anything#10]
Cool tool. Testing it for our experiments and running into issues. see attached image. There're 3 blocks of "error" after I uploaded the video. I don't have any controls to try and do anything (buttons don't do anything).

![image (2)](https://user-images.githubusercontent.com/2547204/234299165-f4c62a2b-a53c-4452-ba3f-0ec016d69eb7.png)

**Comment by LwAiBug** [comment]
Maybe you can try to see if there are any errors in your console

**Comment by memoryunreal** [comment]
Thanks for your interest. Please provide more details for us to reproduce, or you can try to git clone this repo and run it in your environment to see the terminal output and provide the logs to us.
