### ISSUE TITLE
PytorchStreamReader error failed reading zip archive

### ISSUE THREAD

**Issue by frank6200db** [gaomingqi/Track-Anything#103]
Hi,  thanks for all your hardwork.
However, as I launch python app.py --device cuda:0 
'RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory' occurs.
Since the urls have been successfully downloaded, can you help figure out how to deal with this issue? Thanks for your time.

**Comment by frank6200db** [comment]
Problem solved

**Comment by vedantroy** [comment]
How was the problem solved? I am also running into this issue

**Comment by zengy5** [comment]
@vedantroy maybe your .pth file is not incomplete, I suggest you download them again
