### ISSUE TITLE
Can this run under win11? Is it possible to make compatibility adjustments for Win11 in the future?

### ISSUE THREAD

**Issue by Baituhao** [gaomingqi/Track-Anything#11]
I configured the environment and successfully lauched in powershell , but the web interface cannot be opened under win11. Is it possible to make compatibility adjustments for Win11 in the future?

**Comment by teidenzero** [comment]
What are your steps to launch the web interface?

**Comment by zh-plus** [comment]
We tested this project on the Windows platform using a 3080-8G GPU (with `--sam_model_type vit_b`). Feel free to report any issues you encounter while running it on Windows.

**Comment by zh-plus** [comment]
> What are your steps to launch the web interface?

Please refer to the [Get Started](https://github.com/gaomingqi/Track-Anything#get-started) section.

**Comment by funnyalias** [comment]
Note that the terminal or powershell window will give you http://0.0.0.0:6080/ as the address to open the web ui. Under Windows I had to change this to http://127.0.0.1:6080/ for the web browser to connect and display the interface.

**Comment by zh-plus** [comment]
> Note that the terminal or powershell window will give you http://0.0.0.0:6080/ as the address to open the web ui. Under Windows I had to change this to http://127.0.0.1:6080/ for the web browser to connect and display the interface.

Yes, `0.0.0.0:6080` is intended for a GUI-less server. We will include this updated address information in the README.
