### ISSUE TITLE
Packages & Python Versions

### ISSUE THREAD

**Issue by IgorHoholko** [gaomingqi/Track-Anything#12]
Hello, thanks for the library.
Could you please provide version of Python and `requirements.txt` with fixed versions? 

Getting errors installing the package as it is.

Even better if you could provide a docker container.

**Comment by IgorHoholko** [comment]
That helped:
```bash
pip install -U openmim
mim install mmengine
mim install "mmcv>=2.0.0"
```

**Comment by tomatopuree** [comment]
confirming this fix works with python3.9.16 on Ubuntu 18.04
