### ISSUE TITLE
ERROR: Failed building wheel for mmcv-full

### ISSUE THREAD

**Issue by oliverban** [gaomingqi/Track-Anything#14]
installing reqs ends with this:
      active_rotated_filter.cpp
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\include\yvals.h(17): fatal error C1083: Cannot open include file: 'crtdbg.h': No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mmcv-full
  Running setup.py clean for mmcv-full
Successfully built metaseg thinplate segment-anything
Failed to build pycocotools mmcv-full
ERROR: Could not build wheels for pycocotools, mmcv-full, which is required to install pyproject.toml-based projects

C:\Users\XXXXX\Documents\Github\track-anything>

**Comment by gaomingqi** [comment]
Hello, we have updated the requirements and the way installing mmcv, please check our latest push

**Comment by lalamax3d** [comment]
in my case, this failed initially as well. i followed intructions on their git hub [readme](https://github.com/open-mmlab/mmcv)

```bash
pip install -U openmim
mim install mmcv
```

**Comment by memoryunreal** [comment]
We avoid using pip install mmcv, replace with pip install openmim, https://github.com/gaomingqi/Track-Anything/blob/35850bdb735d1544ca0927094c5b21978282cce3/requirements.txt#L15 and run the mim install mmcv in app.py https://github.com/gaomingqi/Track-Anything/blob/35850bdb735d1544ca0927094c5b21978282cce3/app.py#L19-L22
