### ISSUE TITLE
how to make masks fully opaque , rather than semi transparent overlay

### ISSUE THREAD

**Issue by lalamax3d** [gaomingqi/Track-Anything#15]
hey, 
1- huge thanks, i was testing (linux / local install) working great and amazing speed. 3 sec , 720 p clip gets masked in 3 secs, what a time to be alive.

Q. is it possble to make mask fully  opaque.. i.e orange color fully solid??
![Screenshot_20230426_080813](https://user-images.githubusercontent.com/567387/234458891-2233a0a1-9603-4188-9f7c-d7862e2d5e66.png)

**Comment by gaomingqi** [comment]
hello, we provide interfaces in mask_painter to change the mask transparency (default value is 0.7) and colour (default value is orange).

https://github.com/gaomingqi/Track-Anything/blob/91f020ee35ffd1c84e439bf931172d4e22cc41d2/tools/painter.py#L137

You can make mask fully opaque by setting mask_alpha as 1 when calling mask_painter. 

BTW, mask_painter takes the index of colour as input and below is the colormap we are using: 

![colormap](https://user-images.githubusercontent.com/28050374/234475381-47f7b60a-6bf7-4246-a939-7bf79e414f13.png)
