### ISSUE TITLE
about  run error

### ISSUE THREAD

**Issue by zhanghongyong123456** [gaomingqi/Track-Anything#21]
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
![image](https://user-images.githubusercontent.com/48466610/234747087-6d501993-613e-4f2d-a28b-7d8354c812f1.png)

**Comment by zh-plus** [comment]
Please provide a more detailed description of how to reproduce this issue, including the following:
- Steps taken on the GUI.
- The version of Python and Gradio being used.

**Comment by zhanghongyong123456** [comment]
> Please provide a more detailed description of how to reproduce this issue, including the following:
> 
> * Steps taken on the GUI.
> * The version of Python and Gradio being used.

![image](https://user-images.githubusercontent.com/48466610/234773799-45c6d064-08b9-4471-bd1c-a04a14a55e83.png)
: windows 10 
[environmental information]:
python: 3.9.16
Gradio: 3.25.0 
gradio-client:0.1.3
torch:  2.0 cuda 11.7 
mmcv:2.0

**Comment by zhanghongyong123456** [comment]
> > Please provide a more detailed description of how to reproduce this issue, including the following:
> > 
> > * Steps taken on the GUI.
> > * The version of Python and Gradio being used.
> 
> ![image](https://user-images.githubusercontent.com/48466610/234773799-45c6d064-08b9-4471-bd1c-a04a14a55e83.png) : windows 10 [environmental information]: python: 3.9.16 Gradio: 3.25.0 gradio-client:0.1.3 torch: 2.0 cuda 11.7 mmcv:2.0

![image](https://user-images.githubusercontent.com/48466610/234776190-3ad11f5d-1c58-461a-90f1-46eb777aae08.png)

**Comment by zh-plus** [comment]
Regarding `ConnectionResetError`, it may be due to an issue with the version of Gradio. You can try updating Gradio using `pip install gradio -U`.

As for the inpaint error, kindly monitor the progress of issue #22.
