### ISSUE TITLE
Improve object tracking for objects that temporarily disappear and reappear in the video

### ISSUE THREAD

**Issue by DavidTu21** [gaomingqi/Track-Anything#24]
Hi all,

First of all, I would like to thank you again for your amazing work! I have successfully used it in my application, and it performs really well! However, I have noticed a performance issue that I would like to address to further improve the tracking capabilities of the model.

When tracking ONE object, if the object disappears (entirely) from the video for a few frames and then reappears, the model seems to struggle to identify it again, without using human interactions. I understand this is a common issue. However, I am wondering if there is anything I could modify in the code to enhance the model's ability to track objects that temporarily disappear and reappear in the video.

Any suggestions or guidance would be greatly appreciated. Thank you in advance!

Best regards,

**Comment by gaomingqi** [comment]
Hello, one way to enhance the model's ability is to increase the number of max memory frames (larger memory bank can enable the model to identify more diverse appearance of the target object). You can specify a larger value to max_mid_term_frames:

https://github.com/gaomingqi/Track-Anything/blob/57c28bc6b6288f792435f8ddd6830626b2b7cf10/tracker/config/config.yaml#L4

:balloon: Note that doing so would cause more GPU memory usage. Thanks.

**Comment by DavidTu21** [comment]
thank you for the advice, I will give it a try!
