### ISSUE TITLE
大佬，为什么我运行不了呢

### ISSUE THREAD

**Issue by ycyjy** [gaomingqi/Track-Anything#25]
(venv) D:\Track-Anything-master>python app.py
Initializing BaseSegmenter to cuda:0
Traceback (most recent call last):
  File "D:\Track-Anything-master\app.py", line 383, in <module>
    model = TrackingAnything(SAM_checkpoint, xmem_checkpoint, e2fgvi_checkpoint,args)
  File "D:\Track-Anything-master\track_anything.py", line 18, in __init__
    self.samcontroler = SamControler(self.sam_checkpoint, args.sam_model_type, args.device)
  File "D:\Track-Anything-master\tools\interact_tools.py", line 37, in __init__
    self.sam_controler = BaseSegmenter(SAM_checkpoint, model_type, device)
  File "D:\Track-Anything-master\tools\base_segmenter.py", line 25, in __init__
    self.model = sam_model_registry[model_type](checkpoint=SAM_checkpoint)
  File "C:\ana\lib\site-packages\segment_anything\build_sam.py", line 15, in build_sam_vit_h
    return _build_sam(
  File "C:\ana\lib\site-packages\segment_anything\build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "C:\ana\lib\site-packages\torch\serialization.py", line 777, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\ana\lib\site-packages\torch\serialization.py", line 282, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
是torch版本不对吗？

**Comment by memoryunreal** [comment]
Try to download [sam_vit_h](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth) manually and then move it to/checkpoints directory. The error shows that your SAM checkpoint is corrupted.

**Comment by ycyjy** [comment]
same error happened！！ Is others file corruted too？

![111111](https://user-images.githubusercontent.com/96721046/234807787-0d1b785e-6fae-4a2a-bfdc-276d48054bd9.png)

**Comment by memoryunreal** [comment]
Please show the output info, and the Xmem checkpoints' size is not correct.

**Comment by ycyjy** [comment]
Okay，i have download all file，but the new error happened when I run app.py and click "get vide
![222](https://user-images.githubusercontent.com/96721046/234823971-64546a3f-4e35-432d-bc2f-d26127a1deda.png)
o info"

**Comment by memoryunreal** [comment]
It's better to show with the terminal (or vscode or pycharm) output, it seems your app server is down, as the error shows.

**Comment by ycyjy** [comment]
![5456464](https://user-images.githubusercontent.com/96721046/234825629-be2334dd-c920-47fa-b9c3-d578bbdcd102.png)
this is my terminal

**Comment by memoryunreal** [comment]
refresh your browser and try again.

**Comment by memoryunreal** [comment]
Sorry, I cannot reproduce your problem. Please make sure you are connecting to localhost:7861.

**Comment by ycyjy** [comment]
Can i add your wechat？I am sure i am connecting to localhost：7861

**Comment by memoryunreal** [comment]
You can record the operation video (contain the terminal output) and send it to my email: zhe.li.cs@outlook.com

**Comment by ycyjy** [comment]
okay，I have send email,please check it!

**Comment by Schweizliu** [comment]
为什么我一直卡在download checkpoints ......上，有人遇到过吗
