### ISSUE TITLE
masks displayed from multiple frames

### ISSUE THREAD

**Issue by fferroni** [gaomingqi/Track-Anything#38]
Hi,

Nice work!

1. Using the demo app, whenever one clicks on a "Add mask" and then switches to a new frame, and then adds another mask, _all_ masks from all time steps are displayed. Perhaps it would be better to display only masks associated to a particular frame?
2. If multiple masks are selected of the same object over a longer video sequence, they interpreted as separate tracked objects and not merged. How can one select in the UI multiple occurrences of the same track?

Also, I often get the following error
```
in generate_video_from_frames
    frames = torch.from_numpy(np.asarray(frames))
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (200,) + inhomogeneous part.
```

**Comment by gaomingqi** [comment]
Hello, thanks for your feedback! 

For the first issue, the current version of Track-Anything starts tracking from masks on one frame only. So adding masks on multiple frames would cause unknown displays and errors. 

For the second issue, Track-Anything now does not support merging multiple masks of the same object. 

Starting from multiple frames is a very good idea! And we will consider this in our future features. 

For the last error, we have recently received several feedback about this, and we will let you know if we solve it. 

Thanks.

**Comment by fferroni** [comment]
Indeed, if there are some objects going into the video frame after others, it's unfortunate not to be able to track them from later prompts. Anyhow, will close the issue for now.
