### ISSUE TITLE
Multiple Object Tracking automation

### ISSUE THREAD

**Issue by brucemuller** [gaomingqi/Track-Anything#47]
Thanks for your work. I was wondering if there is any support for automatic multiple object tracking?

**Comment by gaomingqi** [comment]
Hello. Track-Anything does not support automatic multiple object tracking. But it can be shifted to do so if one can convert prompts from user-provided points to evenly-sampled points. Thanks.

**Comment by brucemuller** [comment]
> Hello. Track-Anything does not support automatic multiple object tracking. But it can be shifted to do so if one can convert prompts from user-provided points to evenly-sampled points. Thanks.

Thank you! Will do :)
