### ISSUE TITLE
Where does "inpainter" come from?

### ISSUE THREAD

**Issue by XinyueZ** [gaomingqi/Track-Anything#50]
Hey guys,

is the inpainter(https://github.com/gaomingqi/Track-Anything/tree/master/inpainter) origin from this repo or from other project (standalone)?

thanks.

**Comment by gaomingqi** [comment]
Hello, "inpainter" in Track-Anything is wrapped from E2FGVI: 

https://github.com/gaomingqi/Track-Anything/blob/65588bb237934ea07b079ef9f08e913d9aeb7477/README.md?plain=1#L98

E2FGVI is a standalone and excellent project for video inpainting ("Towards An End-to-End Framework for Flow-Guided Video Inpainting", CVPR 2022). Check their [paper](https://arxiv.org/abs/2204.02663) or [repo](https://github.com/MCG-NKU/E2FGVI) for more details. Thanks.
