### ISSUE TITLE
ImportError: cannot import name 'SegAutoMaskPredictor' from partially initialized module 'metaseg' (most likely due to a circular import) (/root/anaconda3/lib/python3.10/site-packages/metaseg/__init__.py)

### ISSUE THREAD

**Issue by Sequential-circuits** [gaomingqi/Track-Anything#6]
(base) root@185:~/Track-Anything# python app.py --device cuda:0 --sam_model_type vit_h --port 80
Traceback (most recent call last):
  File "/root/Track-Anything/app.py", line 2, in <module>
    from demo import automask_image_app, automask_video_app, sahi_autoseg_app
  File "/root/Track-Anything/demo.py", line 1, in <module>
    from metaseg import SegAutoMaskPredictor, SegManualMaskPredictor, SahiAutoSegmentation, sahi_sliced_predict
  File "/root/anaconda3/lib/python3.10/site-packages/metaseg/__init__.py", line 7, in <module>
    from metaseg.falai_demo import falai_automask_image, falai_manuelmask_image
  File "/root/anaconda3/lib/python3.10/site-packages/metaseg/falai_demo.py", line 5, in <module>
    from metaseg import SegAutoMaskPredictor, SegManualMaskPredictor
ImportError: cannot import name 'SegAutoMaskPredictor' from partially initialized module 'metaseg' (most likely due to a circular import) (/root/anaconda3/lib/python3.10/site-packages/metaseg/__init__.py)

**Comment by gaomingqi** [comment]
Hello, please specify another version of metaseg, for example, 0,6,1 or 0.7.3 as discussed [here](https://github.com/kadirnar/segment-anything-video/issues/61). Thanks.
