### ISSUE TITLE
app.py: error: unrecognized arguments:

### ISSUE THREAD

**Issue by jotatx** [gaomingqi/Track-Anything#9]
First of all this is an outstanding project.

unfortunately i could not replicate it here, since this error prevents the server to run.

python app.py --device cuda:0 -sam_model_type vit_h --port 12212
usage: app.py [-h] [--device DEVICE] [--sam_model_type SAM_MODEL_TYPE]
              [--port PORT] [--debug] [--mask_save MASK_SAVE]

app.py: error: unrecognized arguments: -sam_model_type vit_h

any tip to what to do, before I try to fix it myself?

cheers

**Comment by gaomingqi** [comment]
hello, try python app.py --device cuda:0 --sam_model_type vit_h --port 12212

**Comment by gaomingqi** [comment]
lost one '-' for sam_model_type

**Comment by jotatx** [comment]
That was pretty fast.  Thank you.

Em ter., 25 de abr. de 2023 10:23, Mingqi Gao ***@***.***>
escreveu:
