### ISSUE TITLE
Purpose of demo.py & metaseg

### ISSUE THREAD

**Issue by egeozguroglu** [gaomingqi/Track-Anything#91]
Hi! Thanks for the great work. Could you please clarify the purpose of [demo.py ](https://github.com/gaomingqi/Track-Anything/blob/master/demo.py)in this package? Isn't this directly the demo of the metaseg package, which I believe does not support video tracking? https://github.com/kadirnar/segment-anything-video

As far as I understand, there is no direct connection between metaseg and Track Anything? Is this accurate?

**Comment by egeozguroglu** [comment]
@kadirnar @gaomingqi

**Comment by kadirnar** [comment]
> Hi! Thanks for the great work. Could you please clarify the purpose of [demo.py ](https://github.com/gaomingqi/Track-Anything/blob/master/demo.py)in this package? Isn't this directly the demo of the metaseg package, which I believe does not support video tracking? https://github.com/kadirnar/segment-anything-video
> 
> As far as I understand, there is no direct connection between metaseg and Track Anything? Is this accurate?

They shared the code I wrote without reference. It's really sad.

Orijinal Code:
https://github.com/kadirnar/segment-anything-video/blob/main/metaseg/sahi_predict.py

Output: 
<img width="700" alt="teaser" src="https://github.com/kadirnar/segment-anything-pip/releases/download/v0.5.0/sahi_autoseg.png">

SAHI: https://github.com/obss/sahi
If you want to detect small objects, you should use SAHI library.
Demo:  https://huggingface.co/spaces/ArtGAN/Segment-Anything-Video

The Track-Anything repo doesn't use the metaseg library.
https://github.com/gaomingqi/Track-Anything/commit/16a97abfa4573b3b6c4cd55d699278d642b64884

**Comment by egeozguroglu** [comment]
Thanks!
